In [1]:
import pandas as pd
import numpy as np

from sklearn import datasets

In [2]:
X, y = datasets.load_breast_cancer(return_X_y = True, as_frame=True)

In [3]:
X.shape

(569, 30)

In [4]:
y.unique()

array([0, 1])

In [5]:
sum(y==0)

212

In [6]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [7]:
X.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [8]:
np.corrcoef(X['mean perimeter'],X['mean radius'])

array([[1.        , 0.99785528],
       [0.99785528, 1.        ]])

In [9]:
M = [[7, 16, 31], [np.nan, np.nan, 66], [12, 5, np.nan],[98, np.nan, 92]]

In [10]:
from sklearn.impute import SimpleImputer

In [11]:
si = SimpleImputer()
si.fit_transform(M)

array([[ 7. , 16. , 31. ],
       [39. , 10.5, 66. ],
       [12. ,  5. , 63. ],
       [98. , 10.5, 92. ]])

In [12]:
M = [[1, 1], [2, 3],[10,100]]

In [13]:
from sklearn.preprocessing import FunctionTransformer

In [14]:
FunctionTransformer(func=np.log).fit_transform(M)

array([[0.        , 0.        ],
       [0.69314718, 1.09861229],
       [2.30258509, 4.60517019]])

In [15]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header=None)

In [16]:
df

0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [17]:
from sklearn.preprocessing import PolynomialFeatures

In [18]:
from sklearn.preprocessing import OrdinalEncoder

df[4] = OrdinalEncoder().fit_transform(np.array(df[4]).reshape(-1,1))

In [19]:
df2 = pd.DataFrame(PolynomialFeatures(degree = 2).fit_transform(df.iloc[:,:4]))

In [20]:
df2.shape

(150, 15)

In [21]:
X,y = datasets.fetch_california_housing(return_X_y=True, as_frame=True)

In [22]:
X

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [23]:
from sklearn.feature_selection import mutual_info_regression

In [24]:
from sklearn.feature_selection import SelectPercentile

In [25]:
(SelectPercentile(percentile=10).fit_transform(X,y)).shape

(20640, 1)

In [26]:
mutual_info_regression(X,y)

array([0.38745483, 0.03325641, 0.10316844, 0.02343382, 0.0211907 ,
       0.07243158, 0.36903079, 0.40354675])

In [27]:
X.shape[0]/5*4

16512.0

In [28]:
X.shape

(20640, 8)

In [29]:
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = .2)

In [31]:
y_pred = y_train.mean()

In [32]:
y_pred = [y_pred for i in range(16512)]

In [33]:
r2_score(y_train, y_pred)

0.0

In [34]:
from sklearn.preprocessing import MinMaxScaler

In [43]:
scaler = MinMaxScaler()
X_train = pd.DataFrame(scaler.fit_transform(X_train))
X_test = pd.DataFrame(scaler.transform(X_test))

In [44]:
from sklearn.linear_model import SGDRegressor

In [45]:
model = SGDRegressor()
model.fit(X_train,y_train)

SGDRegressor()

In [46]:
from sklearn.metrics import mean_absolute_error

In [47]:
y_pred = model.predict(X_test)
mean_absolute_error(y_test, y_pred)

0.5699603442561456

In [48]:
mean_absolute_error(y_train, model.predict(X_train))

0.5594302460169319

In [49]:
from sklearn.linear_model import LinearRegression

In [50]:
?SGDRegressor

In [84]:
X_diabetes, y_diabetes = datasets.load_diabetes(return_X_y=True, as_frame = True)

In [85]:
X_diabetes.shape

(442, 10)

In [86]:
X_diabetes

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [87]:
from sklearn.preprocessing import StandardScaler

In [88]:
scaler = StandardScaler()

In [89]:
X_diabetes = scaler.fit_transform(X=X_diabetes)

In [90]:
X_train, X_test, y_train, y_test = train_test_split(X_diabetes, y_diabetes, test_size = 0.2, random_state = 10)

In [91]:
model_lr = LinearRegression()

In [92]:
model_lr.fit(X_train, y_train)
model_lr.score(X_test, y_test)

0.5341988244945843

In [93]:
model_lr.coef_

array([ -0.18490165, -10.73190006,  24.63419925,  15.61612821,
       -34.58951403,  19.54679579,   3.81732698,  10.37783679,
        33.49852404,   1.90371458])

In [75]:
X_diabetes

array([[ 0.80050009,  1.06548848,  1.29708846, ..., -0.05449919,
         0.41853093, -0.37098854],
       [-0.03956713, -0.93853666, -1.08218016, ..., -0.83030083,
        -1.43658851, -1.93847913],
       [ 1.79330681,  1.06548848,  0.93453324, ..., -0.05449919,
         0.06015558, -0.54515416],
       ...,
       [ 0.87686984,  1.06548848, -0.33441002, ..., -0.23293356,
        -0.98564884,  0.32567395],
       [-0.9560041 , -0.93853666,  0.82123474, ...,  0.55838411,
         0.93616291, -0.54515416],
       [-0.9560041 , -0.93853666, -1.53537419, ..., -0.83030083,
        -0.08875225,  0.06442552]])

In [97]:
cv = 5
alpha_list = np.logspace(-4, 0, num=20)
Scoring = "neg_mean_absolute_error"

In [98]:
from sklearn.linear_model import RidgeCV

In [99]:
model_rcv = RidgeCV(alphas=alpha_list,cv=cv,scoring=Scoring)

In [100]:
model_rcv.fit(X_train, y_train)

RidgeCV(alphas=array([1.00000000e-04, 1.62377674e-04, 2.63665090e-04, 4.28133240e-04,
       6.95192796e-04, 1.12883789e-03, 1.83298071e-03, 2.97635144e-03,
       4.83293024e-03, 7.84759970e-03, 1.27427499e-02, 2.06913808e-02,
       3.35981829e-02, 5.45559478e-02, 8.85866790e-02, 1.43844989e-01,
       2.33572147e-01, 3.79269019e-01, 6.15848211e-01, 1.00000000e+00]),
        cv=5, scoring='neg_mean_absolute_error')

In [103]:
mean_absolute_error(y_train, model_rcv.predict(X_train))

43.47104306865488