In [ ]:
import pandas as pd
import numpy as np

from sklearn.cluster import KMeans, AgglomerativeClustering

from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.metrics import accuracy_score, r2_score

from sklearn.model_selection import train_test_split

from sklearn.pipeline import Pipeline
from sklearn.neural_network import MLPRegressor

In [ ]:
kmeans = KMeans(random_state=10, n_clusters=2)

In [ ]:
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00488/Live_20210128.csv")

In [ ]:
df

status_id status_type status_published  num_reactions  num_comments  \
0             1       video   4/22/2018 6:00            529           512   
1             2       photo  4/21/2018 22:45            150             0   
2             3       video   4/21/2018 6:17            227           236   
3             4       photo   4/21/2018 2:29            111             0   
4             5       photo   4/18/2018 3:22            213             0   
...         ...         ...              ...            ...           ...   
7045       7046       photo   9/24/2016 2:58             89             0   
7046       7047       photo  9/23/2016 11:19             16             0   
7047       7048       photo  9/21/2016 23:03              2             0   
7048       7049       photo   9/20/2016 0:43            351            12   
7049       7050       photo  9/10/2016 10:30             17             0   

      num_shares  num_likes  num_loves  num_wows  num_hahas  num_sads  \
0            262        432         92         3          1         1   
1              0        150          0         0          0         0   
2             57        204         21         1          1         0   
3              0        111          0         0          0         0   
4              0        204          9         0          0         0   
...          ...        ...        ...       ...        ...       ...   
7045           0         89          0         0          0         0   
7046           0         14          1         0          1         0   
7047           0          1          1         0          0         0   
7048          22        349          2         0          0         0   
7049           0         17          0         0          0         0   

      num_angrys  Column1  Column2  Column3  Column4  
0              0      NaN      NaN      NaN      NaN  
1              0      NaN      NaN      NaN      NaN  
2              0      NaN      NaN      NaN      NaN  
3              0      NaN      NaN      NaN      NaN  
4              0      NaN      NaN      NaN      NaN  
...          ...      ...      ...      ...      ...  
7045           0      NaN      NaN      NaN      NaN  
7046           0      NaN      NaN      NaN      NaN  
7047           0      NaN      NaN      NaN      NaN  
7048           0      NaN      NaN      NaN      NaN  
7049           0      NaN      NaN      NaN      NaN  

[7050 rows x 16 columns]

In [ ]:
df.drop(['Column1','Column2','Column3','Column4'], axis=1, inplace=True)

In [ ]:
X = df.drop('status_type', axis=1)
y = df['status_type']

In [ ]:
X.drop(['status_id','status_published'], axis=1, inplace=True)

In [ ]:
le = LabelEncoder()
scaler = StandardScaler()

In [ ]:
y = le.fit_transform(y)
X = scaler.fit_transform(X)

In [ ]:
X.shape

(7050, 9)

In [ ]:
pd.DataFrame(y).value_counts()

1    4288
3    2334
2     365
0      63
dtype: int64

In [ ]:
kmeans.fit(X,y)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(n_clusters=2, random_state=10)

In [ ]:
kmeans.inertia_

32469.791362309865

In [ ]:
kmeans.inertia_

48278.09824220544

In [ ]:
kmeans.labels_

array([1, 1, 1, ..., 1, 1, 1], dtype=int32)

In [ ]:
ac = AgglomerativeClustering(n_clusters=4,affinity='euclidean',linkage='ward')

In [ ]:
ac.fit(X,y)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_agglomerative.py:983: FutureWarning: Attribute `affinity` was deprecated in version 1.2 and will be removed in 1.4. Use `metric` instead
  warnings.warn(


AgglomerativeClustering(affinity='euclidean', n_clusters=4)

In [ ]:
ac.labels_

array([3, 3, 3, ..., 3, 3, 3])

In [ ]:
ac.n_leaves_

7050

In [ ]:
accuracy_score(y,ac.labels_)

0.2849645390070922

In [ ]:
air = pd.read_csv("/AirQualityUCI.csv")

In [ ]:
air.drop(['Date','Time','Unnamed: 15','Unnamed: 16'], inplace=True, axis=1)

In [ ]:
air.shape

(9471, 13)

In [ ]:
air.dropna(inplace=True)

In [ ]:
air.shape

(9357, 13)

In [ ]:
air.head()

CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  PT08.S2(NMHC)  NOx(GT)  \
0     2.6       1360.0     150.0      11.9         1046.0    166.0   
1     2.0       1292.0     112.0       9.4          955.0    103.0   
2     2.2       1402.0      88.0       9.0          939.0    131.0   
3     2.2       1376.0      80.0       9.2          948.0    172.0   
4     1.6       1272.0      51.0       6.5          836.0    131.0   

   PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)     T    RH      AH  
0        1056.0    113.0        1692.0       1268.0  13.6  48.9  0.7578  
1        1174.0     92.0        1559.0        972.0  13.3  47.7  0.7255  
2        1140.0    114.0        1555.0       1074.0  11.9  54.0  0.7502  
3        1092.0    122.0        1584.0       1203.0  11.0  60.0  0.7867  
4        1205.0    116.0        1490.0       1110.0  11.2  59.6  0.7888

In [ ]:
np.corrcoef(air['T'],air['RH'])


array([[1.        , 0.88591052],
       [0.88591052, 1.        ]])

In [ ]:
y = air['AH']
air.drop('AH', axis=1, inplace=True)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(air, y, random_state=1, test_size=0.2)

In [ ]:
pipe = Pipeline([('scaler',StandardScaler()),
                 ('model',MLPRegressor(hidden_layer_sizes=50,
                                       tol=1e-2,
                                       alpha=1e-4,
                                       solver="adam",
                                       learning_rate_init=0.1,
                                       max_iter=50,
                                       random_state=1))
                 ])

In [ ]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model',
                 MLPRegressor(hidden_layer_sizes=50, learning_rate_init=0.1,
                              max_iter=50, random_state=1, tol=0.01))])

In [ ]:
X_test.shape

(1872, 12)

In [ ]:
y_pred = pipe.predict(X_test)

In [ ]:
y_pred_train = pipe.predict(X_train)

In [ ]:
pipe[1].n_layers_

3

In [ ]:
r2_score(y_pred_train, y_train)

0.9999647422627423

In [ ]:
r2_score(y_pred, y_test)

0.9999597673692345

In [ ]:
y_pred_train

array([1.63773849, 0.73866524, 0.37303465, ..., 1.07966996, 0.74808393,
       1.11660365])