# 7A

## Part 1

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df = pd.read_csv("data_for_large_scale.csv")

In [ ]:
X, y = df.drop("Target", axis=1), df.Target

In [ ]:
X

Feature-1  Feature-2  Feature-3  Feature-4  Feature-5  Feature-6  \
0         -1.580     1.0500     1.0600     -0.440    0.45100    -0.0348   
1         -0.832    -0.8660    -1.3400      0.138    1.18000     0.7330   
2         -0.237     2.0900    -3.9300      0.296    0.35200    -0.5010   
3         -1.170    -1.1300    -1.0900      1.120    0.31200     0.1830   
4          0.260    -0.0273     0.9250     -1.150   -1.39000     0.0251   
...          ...        ...        ...        ...        ...        ...   
89995     -0.268    -0.3200    -0.0146     -0.251    1.76000     0.8590   
89996     -0.774     0.4960     1.9400      0.673    0.29500    -0.0137   
89997      0.509    -0.3220     0.6810     -0.276   -0.00553    -1.1000   
89998      0.360     1.2500     0.6510     -0.871    0.37900     0.7690   
89999     -0.860    -0.6010     0.7390      0.190   -0.33100    -1.2700   

       Feature-7  Feature-8  Feature-9  Feature-10  
0          0.643     0.2650      0.268     -0.8510  
1         -1.410     0.1350     -0.088     -1.5500  
2          0.961    -0.0287      1.820      0.9380  
3          0.448    -0.8190     -1.010     -1.0800  
4          0.627     0.0950     -0.280     -0.8480  
...          ...        ...        ...         ...  
89995     -1.090    -1.3800      1.760     -1.0900  
89996     -0.966    -0.6270     -0.113      0.0767  
89997      0.453     0.7270     -1.940     -2.0100  
89998      1.330    -0.3670     -1.280     -1.1000  
89999     -2.610    -0.4830     -1.380      1.1100  

[90000 rows x 10 columns]

In [ ]:
y

0         84.70
1       -211.00
2        -96.90
3       -152.00
4        -57.70
          ...  
89995     -4.15
89996     63.50
89997    -80.20
89998    158.00
89999   -369.00
Name: Target, Length: 90000, dtype: float64

In [ ]:
X_array = np.array(X)
y_array = np.array(y)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_array,y_array,test_size=0.3, random_state=10)

In [ ]:
X_train

array([[ 0.224 ,  0.631 ,  0.639 , ..., -1.54  ,  1.03  , -0.17  ],
       [-1.01  ,  0.118 ,  0.781 , ...,  0.7   , -0.249 , -1.05  ],
       [ 1.97  , -0.358 ,  0.297 , ..., -0.411 ,  0.214 , -1.23  ],
       ...,
       [ 1.3   , -0.828 , -0.369 , ..., -0.315 , -1.8   ,  0.678 ],
       [-0.977 ,  0.254 ,  0.582 , ..., -0.0417,  0.806 , -0.496 ],
       [-0.141 , -0.831 , -0.199 , ...,  0.186 ,  0.94  , -0.782 ]])

In [ ]:
# X_train = X_train.reshape(700,900)
# y_train = y_train.reshape(700,90)

In [ ]:
from sklearn.linear_model import SGDRegressor

In [ ]:
sgd = SGDRegressor(random_state=10)

In [ ]:
sgd.partial_fit(X_train, y_train)

SGDRegressor(random_state=10)

In [ ]:
sgd.score(X_test, y_test)

0.9999919792269896

In [ ]:
sgd.intercept_

array([0.0129126])

In [ ]:
sgd.coef_

array([51.3199055 , 22.28719099, 81.25519798, 53.18468842, 76.46867307,
       71.4904778 , 93.47190994, 51.92473029, 30.03242868, 40.96663737])

In [ ]:
sgd2 = SGDRegressor(random_state=10)
for i in range(5):
  sgd2.partial_fit(X_train,y_train)

In [ ]:
sgd2.coef_, sgd2.intercept_


(array([51.32103682, 22.28450923, 81.25384571, 53.18546677, 76.46446678,
        71.48691903, 93.46865363, 51.92189014, 30.03459338, 40.96756053]),
 array([0.00858904]))

In [ ]:
sgd2.score(X_test,y_test)

0.9999919792269896

In [ ]:
.013 - .005, .013-.105

(0.008, -0.092)

## PART 2

In [77]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDRegressor

In [78]:
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt", sep=",", header=None)
df.head()

0         1          2          3
0  144552912  9.349849  56.740876  17.052772
1  144552912  9.350188  56.740679  17.614840
2  144552912  9.350549  56.740544  18.083536
3  144552912  9.350806  56.740485  18.279465
4  144552912  9.351053  56.740486  18.422974

In [116]:
# df_iter = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt", chunksize=20000,header=None, iterator =True)
# iter = 1
sgd = SGDRegressor(random_state=10)
scaler = StandardScaler()
for chunk in pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt", chunksize=20000,header=None, iterator =True):
  # print(chunk.iloc[:,1:])
  scaler.partial_fit(chunk.iloc[:,0:3])

In [117]:
iter = 1
for chunk in pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt", chunksize=20000,header=None, iterator =True):
  if iter==1:
    df = pd.DataFrame(scaler.transform(chunk.iloc[:,0:3]))
    df_concat = df
    sgd.partial_fit(df.iloc[:,0:3],chunk.iloc[:,3])
    print(iter,sgd.coef_,sgd.intercept_)
  else:
    df = pd.DataFrame(scaler.transform(chunk.iloc[:,0:3]))
    df_concat = pd.concat([df_concat, df])
    sgd.partial_fit(df.iloc[:,0:3],chunk.iloc[:,3])
    print(iter,sgd.coef_,sgd.intercept_)
  iter += 1
df_concat.shape

1 [ 1.875842    5.21037003 -3.76577907] [24.30437982]
2 [ 3.687941    0.15502196 -1.08751599] [20.75026981]
3 [ 6.53121709  2.17104697 -0.48600082] [22.32660814]
4 [ 3.49852173  4.16629272 -4.09791032] [21.75853287]
5 [ 1.51359131  1.09464461 -0.67432443] [21.75041005]
6 [ 0.93578987  4.2011877  -5.49465429] [20.57290015]
7 [-0.19286279  4.81425375 -5.15721844] [21.37692932]
8 [ 3.32032226  4.64466672 -4.61184092] [24.38246111]
9 [ 3.28260035  5.42815013 -5.40226487] [24.83093058]
10 [ 4.34469934  3.66579806 -4.17347813] [22.10028966]
11 [ 2.57232187 -0.86077458  0.65647951] [21.29955348]
12 [ 0.63016193  3.92252157 -4.24700554] [21.7161718]
13 [ 2.81326624  3.70645908 -4.74344336] [21.97293083]
14 [ 2.16043103  3.93874614 -3.8357417 ] [21.99355675]
15 [ 1.04095893 -1.42882052 -2.17346902] [23.18403487]
16 [ 0.06619545 -0.69184066 -3.38497731] [26.89878316]
17 [ 0.45275538  1.2455385  -2.74152831] [22.16329459]
18 [ 2.58959778  2.69714764 -2.04583678] [18.8268134]
19 [-0.60340986  4.75

(434874, 3)

## Part 3

In [120]:
from sklearn import datasets

iris = datasets.load_iris()

In [121]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [122]:
X = iris.data
y = iris.target

In [123]:
iris.target_names, iris.feature_names

(array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'])

In [124]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=10)

In [125]:
from sklearn.neighbors import KNeighborsClassifier

In [133]:
neigh1 = KNeighborsClassifier(n_neighbors=1)
neigh2 = KNeighborsClassifier(n_neighbors=2)
neigh3 = KNeighborsClassifier(n_neighbors=3)
neigh4 = KNeighborsClassifier(n_neighbors=4)
neigh5 = KNeighborsClassifier(n_neighbors=5)

In [134]:
from sklearn.preprocessing import Normalizer

In [135]:
transformer = Normalizer()
transformer.fit(X_train)

Normalizer()

In [136]:
X_train = transformer.transform(X_train)
X_test = transformer.transform(X_test)

In [137]:
neigh2.fit(X_train,y_train)
neigh2.score(X_test,y_test)

0.9666666666666667

In [138]:
neigh3.fit(X_train,y_train)
neigh3.score(X_test,y_test)

0.9666666666666667

In [139]:
neigh4.fit(X_train,y_train)
neigh4.score(X_test,y_test)

0.9666666666666667

In [140]:
neigh1.fit(X_train,y_train)
neigh1.score(X_test,y_test)

0.9666666666666667

In [143]:
from sklearn.metrics import f1_score

f1_score(y_test,neigh3.predict(X_test),average='weighted')

0.9671111111111111

# 7B

## Part 1